server:
  port: 8201

build:
  version: 2.9

spring:
  application:
    name: cards
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://localhost:3306/bank
    Driver: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  config:
    import: "optional:configserver:http://localhost:8071/"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

    #management:
    # endpoints:
    # web:
  #  exposure:
  #    include: "*"
