build:
  version: "1.5"

cards:
  message: "Welcome to SK-PRODUCTION Bank Cards related to locals APIs."
  contactDetails:
    name: "Cards Prod - Principal Software Engineer"
    email: "Sachin12Kansal@gmail.com"
  onCallSupport:
    -(555)555-1234
    -(555)534-0915
