build:
  version: "1.0"

loans:
  message: "Welcome to SK-PRODUCTION Bank Loans related to locals APIs."
  contactDetails:
    name: "Loans Prod - Principal Software Engineer"
    email: "Sachin12Kansal@gmail.com"
  onCallSupport:
    -(555)555-1234
    -(555)534-0915
