server:
  port: 8200

logging:
  level:
    com:
      Sachin:
        Accounts: DEBUG

spring:
  application:
    name: accounts
  profiles:
    active: prod

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/bank
    Driver: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  config:
    import: "optional:configserver:http://localhost:8071/"

  #rabbitmq:
  #  host: "localhost"
  #  port: 5672
  #  username: "guest"
  #  password: "guest"

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      shutdown:
        enabled: true
    info:
      env:
        enabled: true

    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: "Accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 5
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException


