server:
  port: 8071

spring:
  application:
    name: "SpringCloudConfig"
  profiles:
    #active: native
    active: git

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/javasac/ConfigPropsBank.git"
          default-label: master
          timeout: 30
          clone-on-start: true
          force-pull: true

        #native:
          #search-locations: "classpath:/config"
          #search-locations: "https://github.com/javasac/SpringCloudConfig.git"



