server:
  port: 8071

spring:
  application:
    name: "SpringCloudConfig"

  profiles:
    #active: native
    active: git

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/javasac/ConfigPropsBank.git"
          default-label: master
          timeout: 30
          clone-on-start: true
          force-pull: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
