server:
    port: 8210

spring:
  application:
    name: "ConfigServer"

  cloud:
    config:
      server:
        git:
          uri: https://github.com/javasac/
          clone-on-start: true
        bootstrap: true
      enabled: true